general:
  task: "reward_prediction"  #
  random_seed: 42
  use_this_many_data: -1
  use_cuda: True  # disable this when running on machine without cuda
  visdom: False

  training:
    batch_size: 64
    max_episode: 5000000
    smoothing_eps: 0.1
    sample_number: 10
    optimizer:
      step_rule: 'radam'  # adam, radam
      learning_rate: 0.0001
      clip_grad_norm: 5
      learning_rate_warmup_until: 1000
    fix_parameters_keywords: ["rgcns", "word_embedding", "node_embedding", "relation_embedding", "word_embedding_prj"]
    patience: 3  # >=1 to enable

  evaluate:
    run_eval: True
    g_belief: False
    batch_size: 128
    max_target_length: 200

  model:
    use_pretrained_embedding: True
    word_embedding_size: 300
    word_embedding_trainable: False
    node_embedding_size: 100
    node_embedding_trainable: True
    relation_embedding_size: 32
    relation_embedding_trainable: True
    embedding_dropout: 0.
    encoder_layers: 1
    action_scorer_layers: 1
    encoder_conv_num: 5
    block_hidden_dim: 32
    gcn_hidden_dims: [32, 32, 32, 32, 32, 32]  # last one should equal to block hidden dim
    gcn_highway_connections: True
    gcn_num_bases: 3
    real_valued_graph: True
    n_heads: 1
    dropout: 0.
    attention_dropout: 0.
    block_dropout: 0.
    graph_decoding_method: 'ComplEx' # DistMult, ComplEx
    reward_predictor_apply_rnn: True

  checkpoint:
    output_dir: '../saved_models/'
    report_frequency: 2000  # episode
    save_frequency: 10000  # episode
    experiment_tag: 'reward_predictor'
    load_pretrained: True
    load_from_tag: ['graph_auto_encoder_pretrain', 'graph_dynamics_ims', 'reward_predictor']
    load_from_label: ['Mar-04-2021', '', '']
    fix_loaded_parameters: False
    load_partial_parameter_keywords: [] # "rgcns", "word_embedding", "node_embedding", "relation_embedding", "word_embedding_prj"
    load_graph_generation_model_from_tag: 'None'

reward_prediction:
  data_path: "../source/dataset/rp.0.1/"
  graph_type: "seen"
  difficulty_level: 1
