general:
  task: "rl_planning"  #
  random_seed: 42
  use_this_many_data: -1
  use_cuda: True  # disable this when running on machine without cuda
  visdom: False

  training:
    batch_size: 50
    max_episode: 150000
    smoothing_eps: 0.1
    sample_number: 10
    optimizer:
      step_rule: 'radam'  # adam, radam
      learning_rate: 0.00005
      clip_grad_norm: 5
      learning_rate_warmup_until: 1000
      fix_parameters_keywords: ["rgcns", "word_embedding", "node_embedding", "relation_embedding", "word_embedding_prj", "q_target_net"]
      patience: 3  # >=1 to enable

  evaluate:
    run_eval: True
    g_belief: False
    batch_size: 48
    max_target_length: 200

  model:
    use_pretrained_embedding: True
    word_embedding_size: 300
    word_embedding_trainable: False
    node_embedding_size: 100
    node_embedding_trainable: True
    relation_embedding_size: 32
    relation_embedding_trainable: True
    embedding_dropout: 0.
    encoder_layers: 1
    action_scorer_layers: 1
    encoder_conv_num: 5
    block_hidden_dim: 32
    gcn_hidden_dims: [32, 32, 32, 32, 32, 32]  # last one should equal to block hidden dim
    gcn_highway_connections: True
    gcn_num_bases: 3
    real_valued_graph: True
    n_heads: 1
    dropout: 0.
    attention_dropout: 0.
    block_dropout: 0.
    topk_num: 10
    graph_decoding_method: 'ComplEx' # DistMult, ComplEx
    dynamic_model_type: 'linear'
    dynamic_model_mechanism: 'all-independent'
    dynamic_loss_type: 'latent'
    reward_predictor_apply_rnn: True

  checkpoint:
    output_dir: '../saved_models/'
    report_frequency: 100  # episode
    save_frequency: 10000  # episode
    experiment_tag: 'rl_plannning'
    load_pretrained: True
    load_from_tag: ['graph_auto_encoder_pretrain', 'graph_dynamics_ims', 'reward_predictor']
    load_from_label: ['', '', 'Apr-18-2021']  # 'Mar-31-2021'
    data_label: ''
    fix_loaded_parameters: False
    load_partial_parameter_keywords: [] # "rgcns", "word_embedding", "node_embedding", "relation_embedding", "word_embedding_prj"
    load_graph_generation_model_from_tag: 'None'

rl:
  data_path: "rl.0.2"
  triplet_path: "../source/dataset/sp.0.2"
  difficulty_level: 1  # 1-10
  training_size: 100  # 1, 20, 100
  graph_type: "seen"  # full, seen
  simulations_num: 100
  max_scores: 3
  random_move_prob_add: 0.1

  planing:
    planner: 'MCTS'  # CEM, MCTS
    c_puct: 0.01
    discount_rate: 0.6
    load_extractor: False


  training:
    max_nb_steps_per_episode: 50  # after this many steps, a game is terminated
    learn_start_from_this_episode: 100
    target_net_update_frequency: 500  # sync target net with online net per this many epochs
    use_negative_reward: False

  evaluate:
    max_nb_steps_per_episode: 100
